name: 'Add pacman repository'
description: 'Add pacman repository to /etc/pacman.conf'
branding:
  icon: 'archive'  
  color: 'purple'
inputs:
  url:
    description: 'repository URL'
    required: true
  name:
    description: 'name of the repository'
    required: true
  shell:
    description: 'shell to use'
    required: false
    default: bash
runs:
  using: "composite"
  steps:
    - name:
      run: |
        echo -e "[${{ inputs.name }}]" >> /etc/pacman.conf
        echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
        echo "Server = ${{ inputs.url }}" >> /etc/pacman.conf
      shell: ${{ inputs.shell }}
